# Generated by Django 4.2.20 on 2025-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
