# Generated by Django 4.2.20 on 2025-04-25 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_phone_number_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
