# Generated by Django 4.2.20 on 2025-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
